### ISSUE TITLE
Implement Leaderboard V2

### ISSUE THREAD

**Issue by mcao0620** [mcao0620/whenyou#2]
Idea for Approach:
- Store Leaderboard per group as object in Firestore along with timestamp of when it was last updated
- Leaderboard is fetched from Firestore, if leaderboard has not been updated on the current day, the client recalculates and updates the leaderboard for each day from date last updated to today
     - Subsequent requests that will fetch the updated leaderboard

**Comment by eishm721** [comment]
Also, fix ranking calculation with ties issue
